### ISSUE TITLE
add other targets for multiplatform

### ISSUE THREAD

**Issue by shalva97** [saschpe/Kex#8]
Hi, thanks for this lib. I have added it to my project `commonTestImplementation("de.peilicke.sascha:kex:1.1.1")` but getting errors 
```
my-project:nativeTest: Could not resolve de.peilicke.sascha:kex:1.1.1.

my-project:mingwX64Test: Could not resolve de.peilicke.sascha:kex:1.1.1.
```

**Comment by saschpe** [comment]
The project doesn't have `native` and `mingwX64` targets yet. Shouldn't be much work though ...
